<script type="text/javascript">
(function(id) {var jsSrc="//zen.splurgi.com/all-3.js";var js;if(document.getElementById(id)){return;}js=document.createElement('script');js.id= id;js.type="text/javascript";js.src = jsSrc;js.async = true;(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]).appendChild(js);}('splurgy-tab-js'));
window._splurgy_config = window._splurgy_config || []
window._splurgy_config.push({
    // find this token in your admin dashboard where you got this snippet
    token: '$token'
});
</script>
<!-- start Splurgy Embed widget --><script type="text/javascript">
window._splurgy_frames = window._splurgy_frames || [];
window._splurgy_frames.push({
    offer_id: null, // set this value to a specific offer ID to hardcode what is shown
    test_mode: true // set to true to enable diagnostic mode
}); // this embed will expand into the area containing it
</script><div class="splurgy-frame-un"></div><!-- end Splurgy Embed widget -->