<div id="splurgybutton">
<?php

    //Make connection to database
    $databaseconnection = Mage::GetSingleton('core/resource');
    
    $query = 'SELECT status FROM ' . $databaseconnection->getTableName ('splurgy_banner') . ' WHERE entityid = 1';
    $readdata = $databaseconnection->getConnection('core_read');
    $status = $readdata->fetchOne($query);

    if ($status === "1")
    {
        
    //Let url data be read
    $query = 'SELECT bannerimage FROM ' . $databaseconnection->getTableName ('splurgy_banner') . ' WHERE entityid = 1';

    $imagesource = $readdata->fetchOne($query);
    
    echo $this->getButtonEmbed();
    
    $button = '<button type=\'button\' value=\'Earn\' id=\'earncoupon\' name=\'submitcoupon\'>';
    $button .= '<span><img src = ' . $imagesource . '></span>';
    $button .= '</button>';
        
        echo $button;
    }
    ?>
</div>
