<?php

require_once dirname(dirname(__FILE__)) . '/WordpressView.php';

/**
 * Test class for WordpressView.
 * Generated by PHPUnit on 2012-07-10 at 22:52:15.
 */
class WordpressViewTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var WordpressView
     */
    protected $wordpressView;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->wordpressView = new WordpressView;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testPrintMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WordpressView::missingTokenNotice
     * @todo Implement testMissingTokenNotice().
     */
    public function testMissingTokenNotice()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WordpressView::adminMenu
     * @todo Implement testAdminMenu().
     */
    public function testAdminMenu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WordpressView::settingsPage
     * @todo Implement testSettingsPage().
     */
    public function testSettingsPage()
    {

    }

    /**
     * @covers WordpressView::analyticsPage
     * @todo Implement testAnalyticsPage().
     */
    public function testAnalyticsPage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WordpressView::offer
     * @todo Implement testOffer().
     */
    public function testOffer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WordpressView::analyticsEmbed
     * @todo Implement testAnalyticsEmbed().
     */
    public function testAnalyticsEmbed()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WordpressView::addPostMetaBoxOfferList
     * @todo Implement testAddPostMetaBoxOfferList().
     */
    public function testAddPostMetaBoxOfferList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WordpressView::postMetaBoxOfferList
     * @todo Implement testPostMetaBoxOfferList().
     */
    public function testPostMetaBoxOfferList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WordpressView::savePostMetaBoxOfferData
     * @todo Implement testSavePostMetaBoxOfferData().
     */
    public function testSavePostMetaBoxOfferData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
